services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://doadmin:AVNS_60oX1gbkyUjUxv2y63s@db-postgresql-blr1-flomastr-do-user-24629085-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - SUPER_ADMIN_EMAILS=hermann@changemastr.com,service@changemastr.com
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Use Codespaces environment variable if available, otherwise default
      - VITE_API_BASE_URL=${CODESPACE_NAME:+https://${CODESPACE_NAME}-8000.app.github.dev}
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0
